# Change these first 
owner: trinitisolutions # Your GitHub organization or username, where this repository lives
repo: srs-uptime-monitor # The name of this repository

sites:
  - name: Dashboard
    url: https://robot-maatje.com/status
  - name: Admin
    url: https://admin.robot-maatje.com/status
  - name: Robot service
    url: https://srs.triniti.nl/api/robots
    expectedStatusCodes:
      - 200
      - 201
      - 401
  - name: Management service
    url: https://srs.triniti.nl/api/customers
    expectedStatusCodes:
      - 200
      - 201
      - 401
  - name: Dev Dashboard
    url: https://dashboard.srs.appset.nl/status
  - name: Dev Admin
    url: https://admin.srs.appset.nl/status
  - name: Dev Robot service
    url: https://srs.appset.nl/api/robots
    expectedStatusCodes:
      - 200
      - 201
      - 401
  - name: Dev Management service
    url: https://srs.appset.nl/api/customers
    expectedStatusCodes:
      - 200
      - 201
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /srs-uptime-monitor
  logoUrl: https://smartrobot.solutions/wp-content/uploads/2017/02/logo_SmartrobotSolutions-300x87.png
  name: Smartrobot Solutions Maatje platform
  introTitle: "Uptime information of the Maatje Platform"
  introMessage: This page shows the uptime information of all the relevent services of the Maatje Platform
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
